main: com.crimsonwarpedcraft.hitlistener.HitListener
name: OnlyNightPvP
version: "${VERSION}"
api-version: "1.20"
author: lusqua
description: legal
folia-supported: true
commands:
  pvpEnable:
    description: Ativa ou desativa o PvP
    usage: /pvpEnable
#permissions:
#  example.test:
#    description: DESCRIPTION
#    default: true
#  example.*:
#    description: Grants all other permissions
#    default: false
#    children:
